default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: builder_development
  host: localhost
  port: 5432
  username: postgres
  password: password
test:
  <<: *default
  database: builder_test
  host: localhost
  port: 5432
  username: postgres
  password: password
production:
  <<: *default
  database: builder_production
  host: localhost
  port: 5432